version: '3.9'
services:
  backend-base:
    build: ./backend
    environment:
      PORT: ${BACKEND_PORT}
      HOST: 0.0.0.0
      STORAGE_DIR: /data/storage
      REDIS_URL: redis://cache:${REDIS_PORT}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
      ENABLE_DOCS: ${ENABLE_DOCS:-false}
    volumes:
      - storage:/data/storage
    depends_on:
      - cache

  backend:
    extends: backend-base
    profiles: ["prod"]
    environment:
      ENABLE_DOCS: 'false'
    ports:
      - "${BACKEND_HOST_PORT}:${BACKEND_PORT}"

  dev-backend:
    extends: backend-base
    profiles: ["dev"]
    environment:
      ENABLE_DOCS: 'true'
    ports:
      - "${BACKEND_HOST_PORT}:${BACKEND_PORT}"

  cache:
    image: redis:7-alpine
    command: redis-server --port ${REDIS_PORT}
    ports:
      - "${REDIS_HOST_PORT}:${REDIS_PORT}"

volumes:
  storage:
