version: '3.9'
services:
  backend:
    build: ./backend
    environment:
      PORT: ${BACKEND_PORT}
      HOST: 0.0.0.0
      STORAGE_DIR: /data/storage
      REDIS_URL: redis://cache:${REDIS_PORT}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY}
    ports:
      - "${BACKEND_HOST_PORT}:${BACKEND_PORT}"
    volumes:
      - storage:/data/storage
    depends_on:
      - cache

  cache:
    image: redis:7-alpine
    command: redis-server --port ${REDIS_PORT}
    ports:
      - "${REDIS_HOST_PORT}:${REDIS_PORT}"

volumes:
  storage:
